// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"source-base/internal/bootstrap"
	"source-base/internal/config"
	"source-base/internal/controller/http"
	"source-base/internal/ent/repository"
	"source-base/internal/service"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config) (*App, func(), error) {
	logger := LoggerProvider(cfg)
	client, cleanup, err := PostgresProvider(cfg)
	if err != nil {
		return nil, nil, err
	}
	engine, cleanup2, err := RedisProvider(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepository := repository.NewUserRepository(client)
	userService := service.NewUserService(userRepository, logger)
	userController := http.NewUserController(userService)
	controllers := bootstrap.InitRouter(userController)
	echo := bootstrap.InitEcho(controllers, logger)
	app := &App{
		Config:  cfg,
		Logger:  logger,
		DB:      client,
		Redis:   engine,
		EchoApp: echo,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
