server:
  address: "0.0.0.0:8080"
  port: "8080"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  errorStack: false
  errorLogEnabled: false
  errorLogPattern: "error-{Ymd}.log"

logger:
  path: "./log/"
  file: "./logs/{Y-m-d}.log"
  prefix: ""
  level: "info"
  timeFormat: "2006-01-02 15:04:05"
  ctxKeys: ["req", "TraceId"]
  header: true
  stSkip: 1
  stdout: true
  rotateSize: 0
  rotateExpire: 0
  rotateBackupLimit: 0
  rotateBackupExpire: 0
  rotateBackupCompress: 0
  rotateCheckInterval: "1h"
  stdoutColorDisabled: false
  writerColorEnable: true
  flags: 92

postgres:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "mysecretpassword"
  dbname: "app_db"
  sslmode: "disable"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600 # 1h
  conn_max_idle_time: 1800 # 30m
  logger:
    level: "error"
    stdout: true
  debug: true
  timezone: "UTC"

redis:
  default:
    addrs:
      - "127.0.0.1:6379"
    master_name: ""
    host: "127.0.0.1"
    port: 6379
    password: "redispass"
    database: 0

    pool_size: 10000
    min_idle_conns: 10

    pool_timeout: 60
    dial_timeout: 30
    read_timeout: 30
    write_timeout: 30

    max_retries: 3
    min_retry_backoff: 8
    max_retry_backoff: 512

auth:
  jwtKeyId: xoxz-key
  accessTokenExpireMinute: 60
  refreshTokenExpireMinute: 1440
  gracePeriodExpireSecond: 45
  googleClientId: xoxz-key
  rsaPublicKey: public-key
  rsaPrivateKey: private-key

email:
  mailjet_api_key: ${MAILJET_API_KEY}
  mailjet_secret_key: ${MAILJET_SECRET_KEY}
  from_email: xoxz@gmail.com
  from_name: XOXZ Official
  app_url: http://localhost:8080

otel:
  service_name: account-service
  service_version: "1.0.0"
  environment: development # production | staging | development
  exporter_type: grpc # grpc | http
  endpoint: localhost:4317
  sample_rate: 1.0 # 1.0 = 100%, 0.1 = 10%
  insecure: true   # disable TLS (useful for local development)
