// Code generated by ent, DO NOT EDIT.

package generate

import (
	"source-base/internal/ent/generate/pet"
	"source-base/internal/ent/generate/user"
	"source-base/internal/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	petMixin := schema.Pet{}.Mixin()
	petMixinFields0 := petMixin[0].Fields()
	_ = petMixinFields0
	petMixinFields1 := petMixin[1].Fields()
	_ = petMixinFields1
	petMixinFields2 := petMixin[2].Fields()
	_ = petMixinFields2
	petFields := schema.Pet{}.Fields()
	_ = petFields
	// petDescPublicID is the schema descriptor for public_id field.
	petDescPublicID := petMixinFields1[0].Descriptor()
	// pet.DefaultPublicID holds the default value on creation for the public_id field.
	pet.DefaultPublicID = petDescPublicID.Default.(func() string)
	// petDescCreatedAt is the schema descriptor for created_at field.
	petDescCreatedAt := petMixinFields2[0].Descriptor()
	// pet.DefaultCreatedAt holds the default value on creation for the created_at field.
	pet.DefaultCreatedAt = petDescCreatedAt.Default.(func() time.Time)
	// petDescUpdatedAt is the schema descriptor for updated_at field.
	petDescUpdatedAt := petMixinFields2[1].Descriptor()
	// pet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pet.DefaultUpdatedAt = petDescUpdatedAt.Default.(func() time.Time)
	// pet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pet.UpdateDefaultUpdatedAt = petDescUpdatedAt.UpdateDefault.(func() time.Time)
	// petDescID is the schema descriptor for id field.
	petDescID := petMixinFields0[0].Descriptor()
	// pet.DefaultID holds the default value on creation for the id field.
	pet.DefaultID = petDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userMixinFields2 := userMixin[2].Fields()
	_ = userMixinFields2
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescPublicID is the schema descriptor for public_id field.
	userDescPublicID := userMixinFields1[0].Descriptor()
	// user.DefaultPublicID holds the default value on creation for the public_id field.
	user.DefaultPublicID = userDescPublicID.Default.(func() string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields2[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields2[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
